# -*- coding: utf-8 -*-
"""BugeeTech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vB1aTgFs-CDrd73QW6ftFwe9oS2qz3au
"""

import pandas as pd
Vegiees = pd.read_csv("main.csv")
Vegiees.head()

Vegiees.groupby('product_description')['price'].mean()

Vegiees["price_new"] = Vegiees['price'].fillna(
   Vegiees.groupby('product_description')['price'].transform("mean")
)
Vegiees[Vegiees["price"].isna()].head(10)

Vegiees.to_csv('main.csv',index=False)

import pandas as pd
Vegiees = pd.read_csv("main.csv")

Vegiees["sales_amount"] = Vegiees["sales_quantity"].where(
    Vegiees["unit"] != "pcs",
    Vegiees["product_description"].str.split("-", expand=True)[1].astype("float") * \
    Vegiees["sales_quantity"]
)

Vegiees.tail()

Vegiees.to_csv('main.csv',index=False)